INSERT INTO GITHUB_PROJECT(ORG_NAME, REPO_NAME) VALUES ('spring-projects', 'spring-boot');
INSERT INTO GITHUB_PROJECT(ORG_NAME, REPO_NAME) VALUES ('spring-io', 'sagan');
INSERT INTO GITHUB_PROJECT(ORG_NAME, REPO_NAME) VALUES ('spring-io', 'initializr');