INSERT INTO USERS(USERNAME,PASSWORD, ENABLED) VALUES('user1', '{noop}password', 1);
INSERT INTO USERS(USERNAME,PASSWORD, ENABLED) VALUES('user2', '{noop}password', 0);
INSERT INTO USERS(USERNAME,PASSWORD, ENABLED) VALUES('user3', '{noop}password', 1);


INSERT INTO AUTHORITIES(USERNAME,AUTHORITY) VALUES('user1', 'ROLE_USER');
INSERT INTO AUTHORITIES(USERNAME,AUTHORITY) VALUES('user2', 'ROLE_USER');
INSERT INTO AUTHORITIES(USERNAME,AUTHORITY) VALUES('user3', 'ROLE_ADMIN');